#!/usr/bin/env python3
"""SpeakWell backend: serves the static frontend and appraises presentations.

Uses only the Python standard library (no pip install needed).
If ANTHROPIC_API_KEY is set in the environment, appraisals are generated by
Claude. Otherwise a deterministic rule-based appraiser is used so the app
still works fully offline.
"""
import json
import os
import re
import urllib.request
import urllib.error
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

STATIC_DIR = Path(__file__).parent / "static"
PORT = int(os.environ.get("PORT", "8765"))
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "").strip()
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-5")


def clamp(v, lo=0, hi=100):
    return max(lo, min(hi, v))


def pacing_score_fn(wpm):
    # Flat 100 across a comfortable 120-160wpm "ideal" band, then a gentle linear
    # taper outside it (100 points over an 80wpm falloff) rather than a steep single
    # slope — a steep slope hits a hard 0 floor for anything much slower/faster than
    # ideal, making merely-slow (e.g. 77wpm) score identically to silence.
    if wpm <= 0:
        return 0
    if 120 <= wpm <= 160:
        return 100
    if wpm < 120:
        return clamp(round(100 - (120 - wpm) * (100 / 80)))
    return clamp(round(100 - (wpm - 160) * (100 / 80)))


def rule_based_feedback(m):
    wpm = m.get("wpm", 0)
    filler_rate = m.get("fillerRatePer100", 0)
    eye = m.get("eyeContactPct")
    pauses = m.get("pauseCount", 0)
    word_count = m.get("wordCount", 0)
    smile = m.get("smilePct")
    engaged = m.get("engagedExpressionPct")
    dominant_expr = m.get("dominantExpression")
    volume_variation = m.get("volumeVariationDb")
    volume_above_floor_db = m.get("volumeAboveFloorDb")
    tone_variation = m.get("toneVariationSemitones")

    pacing_score = pacing_score_fn(wpm)
    filler_score = clamp(round(100 - filler_rate * 12))
    scores = {"pacing": pacing_score, "fillerWords": filler_score}

    # Eye contact and facial expressiveness are combined into one "body language" pillar
    # since both come from the same webcam face-tracking signal.
    body_language_parts = []
    if eye is not None:
        body_language_parts.append(clamp(round(eye)))
    if engaged is not None:
        body_language_parts.append(clamp(round(engaged)))
    if body_language_parts:
        scores["bodyLanguage"] = round(sum(body_language_parts) / len(body_language_parts))

    # Vocal delivery: some variation is good (emphasis, rhythm); too little reads as
    # monotone/flat, too much reads as erratic. Score peaks at a healthy midpoint.
    # These signals are now measured only from voiced, high-confidence audio frames
    # (silence/pauses and low-confidence pitch estimates are excluded client-side),
    # so a low value here is a real signal, not measurement noise — score it accordingly
    # rather than assuming some baseline variation is always present.
    if tone_variation is not None:
        scores["tone"] = clamp(round(100 - abs(tone_variation - 6) * 9)) if tone_variation >= 3.5 else clamp(round(tone_variation / 3.5 * 55))
    # volume_variation is the dB range between your loudest and softest voiced moments
    # (10th-90th percentile). Unlike tone/pace, a wide deliberate swing here is a good
    # thing, not "erratic" — going from a near-whisper to a projected line is exactly
    # the skill being measured, so this rewards more range monotonically rather than
    # penalizing anything above some assumed "ideal" midpoint.
    if volume_variation is not None:
        scores["volume"] = clamp(round(volume_variation * 100 / 25))

    # Energy: how lively/animated the delivery felt overall — distinct from the
    # variation scores above (which measure modulation/dynamic range). This looks at
    # absolute levels instead: how loud, how brisk, how facially animated, on average.
    # You can have good variation but still read as low-energy overall (soft, slow,
    # flat affect punctuated by rare peaks), or vice versa.
    # Loudness is measured relative to this user's own calibrated mic/room noise floor
    # (not a fixed dBFS number) — raw mic gain varies by 20-30dB across devices for the
    # same real speaking volume, so an absolute threshold can't generalize.
    energy_parts = []
    if volume_above_floor_db is not None:
        energy_parts.append(clamp(round(volume_above_floor_db * 2.2)))
    if wpm:
        energy_parts.append(clamp(round((wpm - 80) * 1.0)))
    if engaged is not None:
        energy_parts.append(clamp(round(engaged)))
    elif smile is not None:
        energy_parts.append(clamp(round(smile * 1.5)))
    energy_score = round(sum(energy_parts) / len(energy_parts)) if energy_parts else None
    if energy_score is not None:
        scores["energy"] = energy_score

    overall = round(sum(scores.values()) / len(scores))

    strengths, improvements, tips = [], [], []

    if 110 <= wpm <= 165:
        strengths.append(f"Solid pacing at about {wpm} words per minute — easy to follow.")
    elif wpm > 165:
        improvements.append(f"You spoke quickly (~{wpm} wpm). Slow down and add pauses after key points.")
        tips.append("Practice pausing for a full breath after each main idea.")
    elif wpm > 0:
        improvements.append(f"Your pace was slow (~{wpm} wpm). Add a touch more energy and momentum.")
        tips.append("Rehearse out loud with a timer to build a brisker, more natural rhythm.")

    if filler_rate <= 2:
        strengths.append("Very few filler words — your delivery sounded clean and confident.")
    elif filler_rate <= 5:
        improvements.append(f"Some filler words crept in (~{filler_rate} per 100 words). Swap them for silent pauses.")
    else:
        improvements.append(f"Filler words were frequent (~{filler_rate} per 100 words). This is the highest-leverage fix.")
        tips.append("Record 30-second drills where the goal is zero filler words, then extend the time.")

    if eye is not None:
        if eye >= 65:
            strengths.append(f"Great camera/eye contact — facing the camera about {eye}% of the time.")
        elif eye >= 35:
            improvements.append(f"Eye contact was inconsistent (~{eye}% facing camera). Anchor your gaze on the lens more.")
        else:
            improvements.append(f"Low eye contact (~{eye}% facing camera). Try placing notes just above the camera.")
            tips.append("Tape a small dot next to the camera lens as a focal point while you practice.")

    # "Engaged" only measures how often the detector read something other than neutral —
    # it says nothing about whether that something was positive. Only praise this as a
    # strength when the dominant expression is actually a positive/energized one;
    # negative-coded dominants (sad, angry, fearful, disgusted) get a hedged note
    # instead, since automated expression detection is also known to misread a relaxed,
    # neutral face as mildly negative — false praise ("your sadness helps hold
    # attention") is worse than no comment here.
    POSITIVE_EXPRESSIONS = {"happy", "surprised"}
    NEGATIVE_EXPRESSIONS = {"sad", "angry", "fearful", "disgusted"}
    if smile is not None and engaged is not None:
        if engaged >= 40 and dominant_expr in POSITIVE_EXPRESSIONS:
            strengths.append(
                f"Expressive delivery — your face was animated (mostly '{dominant_expr}') rather than flat, which helps hold attention."
            )
        elif engaged >= 40 and dominant_expr in NEGATIVE_EXPRESSIONS:
            improvements.append(
                f"Your expression often read as '{dominant_expr}' rather than neutral or positive. This may partly be a quirk of automated "
                "expression detection (it can misread a relaxed face as negative), but worth a look: does your face seem tense on the recording?"
            )
        elif smile >= 25:
            strengths.append("You smiled naturally at points, which reads as warm and approachable.")
        else:
            improvements.append(
                "Your facial expression stayed mostly neutral throughout — a flat expression can read as low energy or disengagement."
            )
            tips.append("Exaggerate your natural expressions slightly on camera; it reads as normal energy on video, not overacting.")

    if tone_variation is not None:
        if 3.5 <= tone_variation <= 10:
            strengths.append(f"Good vocal variety — your pitch ranged about {tone_variation} semitones instead of staying flat.")
        elif tone_variation < 3.5:
            improvements.append(f"Your tone was fairly monotone (~{tone_variation} semitone range). Vary your pitch to emphasize key words.")
            tips.append("Pick one key word per sentence and deliberately raise or lower your pitch on it.")
        else:
            improvements.append(f"Your pitch swung widely (~{tone_variation} semitones) — could read as erratic rather than deliberate.")
            tips.append("Practice controlled emphasis: vary pitch on purpose for 1-2 words per sentence, not constantly.")

    if volume_variation is not None:
        if volume_variation >= 8:
            strengths.append(f"Good vocal dynamics — about {volume_variation}dB between your loudest and softest moments, instead of a flat monotone.")
        else:
            improvements.append(f"Your volume stayed fairly constant throughout (~{volume_variation}dB between loudest and softest). Get louder or softer to emphasize key points.")
            tips.append("Practice dropping your volume slightly on one important phrase, then projecting on the next, to draw the listener in.")

    if energy_score is not None:
        if energy_score >= 70:
            strengths.append("High-energy delivery — your volume, pace, and expressiveness combined to feel lively and engaging.")
        elif energy_score < 40:
            improvements.append("Overall energy felt low-key — soft volume, a slower pace, and a fairly still face combined to feel low-energy.")
            tips.append("Before recording, do 30 seconds of physical warm-up (stand up, stretch, shake out your arms) to raise your energy baseline.")
        else:
            tips.append("Push your energy up a notch: project a little more, pick up the pace slightly, or let your face show more enthusiasm.")

    if pauses <= 2:
        strengths.append("Good use of pacing without long awkward pauses.")
    else:
        improvements.append(f"There were {pauses} long pauses — you may be searching for words. More rehearsal will help.")
        tips.append("Outline your key points as 3-4 short bullets you can glance at, instead of scripting every word.")

    if not strengths:
        strengths.append("You showed up and recorded a full take — that's the hardest part.")
    if not improvements:
        improvements.append("Keep practicing with tougher prompts to build consistency under pressure.")

    summary = (
        f"You spoke for {m.get('durationSec', 0)}s ({word_count} words) on \"{m.get('topic', 'your topic')}\". "
        f"Overall this take scores {overall}/100 — "
        + ("a strong, confident delivery." if overall >= 75 else "solid groundwork with clear next steps." if overall >= 50 else "a good first rep to build from.")
    )

    return {
        "mode": "offline",
        "overallScore": overall,
        "summary": summary,
        "strengths": strengths[:5],
        "improvements": improvements[:5],
        "tips": tips[:4],
        "scoreBreakdown": scores,
    }


def ai_feedback(m):
    prompt = f"""You are an expert public-speaking coach. A user recorded a short practice presentation.
Topic: {m.get('topic')}
Duration: {m.get('durationSec')}s
Word count: {m.get('wordCount')}
Words per minute: {m.get('wpm')}
Filler words per 100 words: {m.get('fillerRatePer100')}
Long pauses (>3s): {m.get('pauseCount')}
Eye contact / facing camera: {m.get('eyeContactPct')}%
Facial expression while speaking: dominant expression was "{m.get('dominantExpression')}", smiled ~{m.get('smilePct')}% of the time, expression was non-neutral (animated/engaged) ~{m.get('engagedExpressionPct')}% of the time. Note: only treat a non-neutral dominant expression as a strength if it's positive (happy/surprised) — if it's negative (sad/angry/fearful/disgusted), don't praise "animation" for its own sake; this is also a lightweight classifier that can misread a relaxed neutral face as mildly negative, so hedge rather than assert it confidently.
Vocal tone variation: pitch ranged about {m.get('toneVariationSemitones')} semitones (mean pitch ~{m.get('meanPitchHz')}Hz) — low means monotone, high means erratic
Volume variation: {m.get('volumeVariationDb')}dB range between loudest and softest voiced moments — low means flat/constant volume, higher means more dynamic (no upper penalty; wide deliberate swings are good)
Volume level relative to this speaker's own ambient room/mic noise floor: {m.get('volumeAboveFloorDb')}dB above floor — higher means louder/more projected, this drives perceived energy
Transcript:
\"\"\"{m.get('transcript', '')[:4000]}\"\"\"

Give an appraisal. Explicitly comment on delivery, not just transcript content: (1) body language — eye contact/camera presence and facial expressiveness (flat/monotone vs animated/engaged, smiling where natural), (2) vocal variety — whether tone/pitch and volume stayed monotone/flat or had natural variation for emphasis, and (3) overall energy — how lively/animated the presenter felt overall based on volume level, pace, and facial engagement (distinct from variation — someone can vary their tone but still come across as low-energy overall, or vice versa). Respond with ONLY valid JSON, no markdown fences, matching exactly this schema:
{{
  "overallScore": <int 0-100>,
  "summary": "<2-3 sentence overall summary>",
  "strengths": ["<specific strength>", ...up to 5],
  "improvements": ["<specific, actionable improvement>", ...up to 5],
  "tips": ["<short practice drill they can try next time>", ...up to 4],
  "scoreBreakdown": {{"pacing": <int>, "fillerWords": <int>, "bodyLanguage": <int>, "tone": <int>, "volume": <int>, "energy": <int>}}
}}"""

    body = json.dumps(
        {
            "model": ANTHROPIC_MODEL,
            "max_tokens": 1024,
            "messages": [{"role": "user", "content": prompt}],
        }
    ).encode("utf-8")

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "content-type": "application/json",
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    text = payload["content"][0]["text"].strip()
    text = re.sub(r"^```(json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()
    data = json.loads(text)
    data["mode"] = "ai"
    return data


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        pass

    def _send_json(self, obj, status=200):
        body = json.dumps(obj).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = self.path.split("?")[0]
        if path == "/":
            path = "/index.html"
        file_path = (STATIC_DIR / path.lstrip("/")).resolve()
        if STATIC_DIR not in file_path.parents and file_path != STATIC_DIR:
            self.send_error(403)
            return
        if not file_path.is_file():
            self.send_error(404)
            return
        ctype = "text/html"
        if file_path.suffix == ".css":
            ctype = "text/css"
        elif file_path.suffix == ".js":
            ctype = "application/javascript"
        data = file_path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_POST(self):
        if self.path != "/api/appraise":
            self.send_error(404)
            return
        length = int(self.headers.get("Content-Length", 0))
        try:
            metrics = json.loads(self.rfile.read(length) or b"{}")
        except json.JSONDecodeError:
            self._send_json({"error": "bad json"}, 400)
            return

        result = None
        if ANTHROPIC_API_KEY:
            try:
                result = ai_feedback(metrics)
            except (urllib.error.URLError, KeyError, json.JSONDecodeError, TimeoutError) as e:
                print("AI feedback failed, falling back to rule-based:", e)
                result = None
        if result is None:
            result = rule_based_feedback(metrics)

        self._send_json(result)


if __name__ == "__main__":
    mode = "AI (Claude)" if ANTHROPIC_API_KEY else "offline rule-based"
    # 0.0.0.0 (not "localhost") so the process accepts connections routed in from
    # outside the container — required for any cloud host, harmless for local dev.
    print(f"SpeakWell server running on port {PORT}  [appraisal mode: {mode}]")
    ThreadingHTTPServer(("0.0.0.0", PORT), Handler).serve_forever()
